#!/usr/bin/env node
// Generated by CoffeeScript 1.3.3
var ArgumentParser, argv, assert, parser, print, test_attributes;

print = console.log;

assert = require('assert');

"In the Python original, negative arguments are accepted\nexcept when there is an option flag that looks like a negative number\ne.g. '-1'";


test_attributes = function(parser) {
  print('expect the 3 group attributes to be same');
  print('parser:', parser._hasNegativeNumberOptionals);
  print('p._opt:', parser._optionals._hasNegativeNumberOptionals);
  print('p._pos:', parser._positionals._hasNegativeNumberOptionals);
  return assert.equal(parser._hasNegativeNumberOptionals, parser._optionals._hasNegativeNumberOptionals);
};

ArgumentParser = require('../lib/argparse').ArgumentParser;

parser = new ArgumentParser({
  debug: true,
  description: 'Argparse example: negative arguments'
});

parser.addArgument(['-x', '--xxx'], {
  nargs: 1,
  help: '1 string argument'
});

parser.addArgument(['-y', '--yyy'], {
  nargs: 1,
  type: 'int',
  help: '1 integer argument'
});

parser.addArgument(['int'], {
  nargs: '*',
  type: 'int',
  help: 'any number of integer arguments'
});

parser.printHelp();

test_attributes(parser);

print('-----------');

print('no arguments');

print(parser.parseArgs([]));

print('-----------');

print("xxx arg: " + (argv = '-x 1'));

print(parser.parseKnownArgs(argv.split(' ')));

print('-----------');

print("xxx neg arg: " + (argv = '-x -1'));

print(parser.parseKnownArgs(argv.split(' ')));

print('-----------');

print("xxx and yyy arg: " + (argv = '-x 1 -y -1'));

print(parser.parseKnownArgs(argv.split(' ')));

print('-----------');

print("xxx and yyy arg: " + (argv = '-x -1 -y -1 -1'));

print(parser.parseKnownArgs(argv.split(' ')));

print('args: ', parser.parseArgs(argv.split(' ')));

print('-----------');

parser.description = "Add numeric option";

parser.addArgument(['-1', '--one'], {
  nargs: 0,
  action: 'storeConst',
  constant: true,
  defaultValue: false,
  help: 'option that looks like negative argument'
});

test_attributes(parser);

parser.printHelp();

print('-----------');

print("xxx arg: " + (argv = '-x 1'));

print('knownArgs', parser.parseKnownArgs(argv.split(' ')));

print('-----------');

print("xxx neg arg: " + (argv = '-1 -2'));

print('knownArgs', parser.parseKnownArgs(argv.split(' ')));

try {
  print('Expect: error: Unrecognized arguments: -2.');
  print(parser.parseArgs(argv.split(' ')));
} catch (error) {
  print(error);
}
